name: "ecommerce_analytics"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "ecommerce_analytics"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  ecommerce_analytics:
    # Staging models (cleaned and typed raw data)
    staging:
      +materialized: view
      +schema: staging

    # Intermediate models (joined and prepped data)
    intermediate:
      +materialized: table
      +schema: intermediate

    # Mart models (final transformed tables for business use)
    marts:
      +materialized: table
      +schema: marts

vars:
  # Source schema where raw data is loaded
  raw_schema: "{{ env_var('DB_SCHEMA', 'olist') }}"
  # Any variables needed for the project
  "dbt_date:time_zone": "America/Sao_Paulo" # Since this is Brazilian e-commerce data

seeds:
  ecommerce_analytics:
    +schema: raw
